--- 
before_install: 
  - "openssl aes-256-cbc -K $encrypted_aa8913b81047_key -iv $encrypted_aa8913b81047_iv -in .travis/secrets.tar.enc -out secrets.tar -d"
bundler_args: "--without development"
language: ruby
matrix: 
  fast_finish: true
  include: 
    - 
      env: PUPPET_GEM_VERSION="3.8.4"
      rvm: "1.9.3"
    - 
      env: PUPPET_GEM_VERSION="3.8.4"
      rvm: "2.1.5"
    - 
      env: "PUPPET_GEM_VERSION=\"~> 4.0\" STRICT_VARIABLES=\"yes\""
      rvm: "2.1.6"
notifications: 
  email: false
  webhooks: 
    on_failure: always
    on_success: change
    urls: 
      - "https://webhooks.gitter.im/e/3477acef6dd93b015c9b"
script: 
  - "bundle exec rake lint"
  - "bundle exec rake validate"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
  - "sh scripts/travis_acceptance.sh"
sudo: false
